<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Annotate\Api\Representation\AnnotationRepresentation $resource
 * @var \Annotate\Api\Representation\AnnotationRepresentation $annotation
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'annotations show');

?>
<?= $this->pageTitle($annotation->displayTitle(), 2) ?>
<h3><?= $translate('Annotation') ?></h3>
<?php $this->trigger('view.show.before'); ?>

<div id="annotation-metadata" class="active section">
    <div class="meta-group">
        <h4><?= $translate('Owner') ?></h4>
        <div class="value"><?= $annotation->linkAnnotator() ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Created') ?></h4>
        <div class="value"><?= $escape($annotation->created()->format('Y-m-d H:i:s')) ?></div>
    </div>
    <h4><?= $translate('Metadata') ?></h4>
    <?= $annotation->displayValues() ?>
</div>

<div id="annotation-bodies" class="active section">
    <?php $bodies = $annotation->bodies(); ?>
    <div class="meta-group">
        <h4 class="annotation-caption"><?= $translate('Bodies') ?></h4>
        <?php if (count($bodies)): ?>
            <?php $i = 0; ?>
            <?php foreach ($bodies as $body): ?>
                <div class="value annotation-body">#<?= ++$i ?></div>
                <?php if ($body->resourceClass()): ?>
                    <div class="meta-group">
                        <h4><?= $translate('Class') ?></h4>
                        <div class="value"><?= $escape($translate($body->resourceClass()->label())) ?></div>
                    </div>
                <?php endif; ?>
                <?= $body->displayValues() ?>
            <?php endforeach; ?>
        <?php else: ?>
            <p class="no-resources"><?= $translate('This annotation has no bodies.') ?></p>
        <?php endif; ?>
    </div>
</div>

<div id="annotation-targets" class="active section">
    <?php $targets = $annotation->targets(); ?>
    <div class="meta-group">
        <h4 class="annotation-caption"><?= $translate('Targets') ?></h4>
        <?php if (count($targets)): ?>
            <?php $i = 0; ?>
            <?php foreach ($targets as $target): ?>
                <div class="value annotation-target">#<?= ++$i ?></div>
                <?php if ($target->resourceClass()): ?>
                    <div class="meta-group">
                        <h4><?= $translate('Class') ?></h4>
                        <div class="value"><?= $escape($translate($target->resourceClass()->label())) ?></div>
                    </div>
                <?php endif; ?>
                <?php // Note: when type + value, it is a selector. ?>
                <?= $target->displayValues() ?>
            <?php endforeach; ?>
        <?php else: ?>
            <p class="no-resources"><?= $translate('This annotation has no targets.') ?></p>
        <?php endif; ?>
    </div>
</div>

<?php $this->trigger('view.show.after'); ?>
