<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Annotate\Api\Representation\AnnotationRepresentation[] $resources
 * @var \Annotate\Api\Representation\AnnotationRepresentation[] $annotations
 * @var \Annotate\Form\QuickSearchForm $formSearch
 * @var \Omeka\Form\ConfirmForm $formDeleteSelected
 * @var \Omeka\Form\ConfirmForm $formDeleteAll
 */

use Annotate\Api\Adapter\AnnotationAdapter;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->headLink()
    ->appendStylesheet($assetUrl('css/annotate-admin.css', 'Annotate'));
$this->headScript()
    ->appendFile($assetUrl('js/annotate-admin.js', 'Annotate'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'annotations browse');

$userIsAllowedBatchUpdate = $this->userIsAllowed(AnnotationAdapter::class, 'batch_update');
$userIsAllowedBatchDelete = $this->userIsAllowed(AnnotationAdapter::class, 'batch_delete');
?>

<?= $this->pageTitle('', 1, $translate('Annotations')) ?>

<?= $this->searchFilters() ?>

 <div class="browse-controls">
    <?= $this->pagination() ?>
    <button type="button" class="search advanced-search quick-search"><?= $escape($translate('Quick Search')) ?></button>
    <?= $this->browse()->renderSortSelector('annotations') ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php if ($annotations): ?>
<form method="post" id="batch-form" class="disable-unsaved-warning">
    <?php if ($userIsAllowedBatchUpdate || $userIsAllowedBatchDelete): ?>
    <div class="batch-inputs">
        <select class="batch-actions-select" name="batch_action" aria-label="<?= $translate('Batch actions') ?>">
            <option value="default"><?= $translate('Batch actions') ?></option>
            <?php if ($userIsAllowedBatchUpdate): ?>
            <option value="update-selected" class="batch-selected" disabled="disabled"><?= $translate('Edit selected') ?></option>
            <option value="update-all"><?= $translate('Edit all') ?></option>
            <?php endif; ?>
            <?php if ($userIsAllowedBatchDelete): ?>
            <option value="delete-selected" class="batch-selected" disabled="disabled"><?= $translate('Delete selected') ?></option>
            <option value="delete-all"><?= $translate('Delete all') ?></option>
            <?php endif; ?>
        </select>
        <div class="batch-actions">
            <button type="button" class="default active" disabled="disabled"><?= $translate('Go') ?></button>
            <?php if ($userIsAllowedBatchUpdate): ?>
            <input type="submit" class="update-selected" name="update_selected" value="<?= $translate('Go') ?>" formaction="<?= $escape($this->url(null, ['action' => 'batch-edit'], true)) ?>">
            <input type="submit" class="update-all" name="update_all" value="<?= $translate('Go') ?>" formaction="<?= $escape($this->url(null, ['action' => 'batch-edit-all'], true)) ?>">
            <?php endif; ?>
            <input type="hidden" name="query" class="batch-query" value="<?= $escape(json_encode($this->params()->fromQuery())) ?>">
            <?php if ($userIsAllowedBatchDelete): ?>
            <a class="delete button sidebar-content delete-selected" data-sidebar-selector="#sidebar-delete-selected"><?= $translate('Go') ?></a>
            <a class="delete button sidebar-content delete-all" data-sidebar-selector="#sidebar-delete-all"><?= $translate('Go') ?></a>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <input type="checkbox" class="select-all" aria-label="<?= $translate('Select all') ?>">
                <?= $translate('Title') ?>
            </th>
            <?= $this->browse()->renderHeaderRow('annotations') ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($annotations as $annotation):
        $userIsAllowedUpdate = $annotation->userIsAllowed('update');
        $userIsAllowedDelete = $annotation->userIsAllowed('delete');
        $resources = $annotation->targetSources();
        ?>
        <tr class="annotation">
            <td>
                <?php if (($userIsAllowedBatchUpdate || $userIsAllowedBatchDelete) && ($userIsAllowedUpdate || $userIsAllowedDelete)): ?>
                <input type="checkbox" name="resource_ids[]" value="<?= $annotation->id() ?>" aria-label="<?= $translate('Select item') ?>"<?php if (!($userIsAllowedUpdate || $userIsAllowedDelete)): ?> disabled="disabled"<?php endif; ?>>
                <?php endif; ?>
                <?= $annotation->linkPretty() ?>
                <?php if (!$annotation->isPublic()): ?>
                    <span class="o-icon-private" aria-label="<?= $translate('Private') ?>"></span>
                <?php endif; ?>
                <ul class="actions">
                    <?php if ($userIsAllowedUpdate): ?>
                    <li><?= $annotation->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $translate('Edit'),
                    ]) ?></li>
                    <?php endif; ?>
                    <?php if ($userIsAllowedDelete): ?>
                    <li><?= $hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $annotation->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $translate('Delete'),
                    ]) ?></li>
                    <?php endif; ?>
                    <li><?= $hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $annotation->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $translate('Details'),
                    ]) ?></li>
                </ul>
            </td>
            <?php echo $this->browse()->renderContentRow('annotations', $annotation); ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<div id="sidebar" class="sidebar">
    <?= $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]) ?>
    <div class="sidebar-content"></div>
</div>

<?php if ($userIsAllowedBatchDelete): ?>
<div id="sidebar-delete-selected" class="sidebar">
    <?= $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]) ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?= $translate('Delete annotations') ?></h3>
            <p><?= $translate('Are you sure you would like to delete the selected annotations?') ?></p>
            <p class="error"><?= sprintf(
                $translate('%s: this action will permanently delete %s annotations and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                '<strong><span id="delete-selected-count"></span></strong>'
            ) ?></p>
            <?= $this->form($this->formDeleteSelected) ?>
        </div>
    </div>
</div>
<div id="sidebar-delete-all" class="sidebar">
    <?= $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]) ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?= $translate('Delete annotations') ?></h3>
            <p><?= $translate('Are you sure you would like to delete all annotations on all pages of this result?') ?></p>
            <p class="error"><?= sprintf(
                $translate('%s: this action will permanently delete %s annotations and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
            ) ?></p>
            <label><input type="checkbox" name="confirm-delete-all-check"> <?= $translate('Are you sure?') ?></label>
            <?= $this->form($this->formDeleteAll) ?>
        </div>
    </div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
    var confirmForm = $(this);
    if ('confirm-delete-all' === this.id) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input[name="resource_ids[]"]:checked:not(:disabled)').each(function() {
            confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
        });
    }
});
$('.delete-all').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-selected'));
});
$('.delete-selected').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-all'));
    var inputs = $('input[name="resource_ids[]"]');
    $('#delete-selected-count').text(inputs.filter(':checked').length);
});
$('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
    $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
});
</script>
<?php endif; ?>

<?php else: ?>

<div class="no-resources">
    <p><?= $translate('Your query returned no annotations.') ?></p>
</div>

<?php endif; ?>

<div id="sidebar-search" class="sidebar search">
    <?= $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]) ?>
    <div class="sidebar-content">
        <div id="sidebar-search-form" class="disable-unsaved-warning">
            <h3><?= $translate('Search annotations') ?></h3>
            <?= $hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'o-icon-search advanced-search']) ?>
            <?= $this->form($formSearch) ?>
        </div>
    </div>
</div>
