<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ConfirmForm $form
 * @var string $resourceLabel
 * @var string $partialPath
 * @var bool $wrapSidebar
 */

$translate = $this->plugin('translate');
$this->form->setButtonLabel('Confirm delete'); // @translate
?>
<?php if ($this->wrapSidebar): ?>
<div id="delete" class="sidebar">
    <?= $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $translate('Close')]) ?>
<?php endif; ?>
    <div id="sidebar-confirm">
        <?php $resourceLabel = $translate($this->resourceLabel); ?>
        <h3><?= sprintf($translate('Delete %s'), $resourceLabel) ?></h3>
        <p><?= sprintf($translate('Are you sure you would like to delete this %s?'), $resourceLabel) ?></p>
        <?= $this->form($this->form) ?>
    </div>
<?php if ($this->wrapSidebar): ?>
</div>
<?php endif; ?>

<?php if (isset($this->partialPath)): ?>
    <?= $this->partial($this->partialPath) ?>
<?php endif; ?>
