<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Annotate\Api\Representation\AnnotationRepresentation $annotation
 * @var \Omeka\Form\ResourceForm $form
 */

$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'annotations edit');
$deleteButton = $annotation->userIsAllowed('delete')
    ? '<a href="#" class="delete button">' . $translate('Delete') . '</a>'
    : null;
?>

<script type='text/javascript'>
<?php
// Most of the time, there will be one body and one target only, with specific
// properties, so the values are merged.
// TODO Improve the form for complex and multiple targets.
?>
var valuesJson = <?= json_encode($annotation->mergedValues()) ?>;
</script>

<?= $this->pageTitle($annotation->displayTitle(), 1, $translate('Annotations'), $translate('Edit')) ?>
<?php $this->trigger('view.edit.before'); ?>
<?php
echo $this->partial('annotate/admin/annotation/form.phtml', [
    'form' => $form,
    'annotation' => $annotation,
    'submitLabel' => $translate('Save'),
    'deleteButton' => $deleteButton,
    'sectionNavEvent' => 'view.edit.section_nav',
    'action' => 'edit',
]);
?>

<?= $this->deleteConfirm($annotation, 'annotation') ?>

<?php $this->trigger('view.edit.after'); ?>
