<?php
/** @var \Annotate\Api\Representation\AnnotationRepresentation $annotation */

$t = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'annotations edit');
$deleteButton = $annotation->userIsAllowed('delete')
    ? '<a href="#" class="delete button">' . $t('Delete') . '</a>'
    : null;
?>

<script type='text/javascript'>
<?php
// Most of the time, there will be one body and one target only, with specific
// properties, so the values are merged.
// TODO Improve the form for complex and multiple targets.
?>
var valuesJson = <?php echo json_encode($annotation->mergedValues()); ?>;
</script>

<?php echo $this->pageTitle($annotation->displayTitle(), 1, $t('Annotations'), $t('Edit')); ?>
<?php $this->trigger('view.edit.before'); ?>
<?php
echo $this->partial('annotate/admin/annotation/form.phtml', [
    'form' => $form,
    'annotation' => $annotation,
    'submitLabel' => $t('Save'),
    'deleteButton' => $deleteButton,
    'sectionNavEvent' => 'view.edit.section_nav',
    'action' => 'edit',
]);
?>

<?php echo $this->deleteConfirm($annotation, 'annotation'); ?>

<?php $this->trigger('view.edit.after'); ?>
