<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()->appendStylesheet($this->assetUrl('css/annotate-admin.css', 'Annotate'));
$this->htmlElement('body')->appendAttribute('class', 'annotations search');
?>

<?= $this->pageTitle($translate('Advanced search'), 1, $translate('Annotations')) ?>
<form id="advanced-search" method="get" action="<?= $escapeAttr($this->url(null, ['action' => 'browse'], true)) ?>">
<?= $this->partial(
    'common/advanced-search',
    ['query' => $query, 'resourceType' => 'annotation']
) ?>
<div id="page-actions">
    <?= $this->hyperlink($translate('Reset'), $this->url(null, [], true), ['class' => 'button']) ?>
    <input type="submit" name="submit" value="<?= $escapeAttr($translate('Search')) ?>">
</div>
</form>
