<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Annotate\Api\Representation\AnnotationRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$annotation = $resource;
?>

<div class="resource-details" data-resource-values="<?php //echo $escape($values); ?>">
    <h3 class="oa-annotation"><?= $annotation->linkPretty() ?></h3>
    <div class="meta-group">
        <?php $owner = $annotation->owner(); ?>
        <h4><?= $escape($translate('Annotator')) ?> <?php if (!$owner): ?><span class="annotation-public"><?= $translate('(public)') ?></span><?php endif; ?></h4>
        <div class="value">
            <?php if ($owner): ?>
            <span class="annotation-email"><?= $hyperlink(
                $owner->email(),
                $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])
            ) ?></span>
            <span class="annotation-name"><?= $escape($owner->name()) ?></span>
            <?php else: ?>
            <?php $annotator = $annotation->annotator(); ?>
            <?php if (is_array($annotator) && !empty($annotator['email'])): ?>
            <span class="annotation-email annotation-public"><?= $hyperlink($escape($annotator['email']), 'mailto:' . rawurlencode($annotator['email'])) ?></span>
            <?php endif; ?>
            <?php if (is_array($annotator) && !empty($annotator['name'])): ?>
            <span class="annotation-name"><?= $escape($annotator['name']) ?></span>
            <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>

    <?= $this->thumbnail($annotation, 'square') ?>
    <div class="meta-group">
        <h4><?= $translate('Visibility') ?></h4>
        <div class="value"><?= ($annotation->isPublic()) ? $escape($translate('Public')) : $escape($translate('Private')) ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Created') ?></h4>
        <div class="value"><?= $escape($annotation->created()->format('Y-m-d H:i:s')) ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Owner') ?></h4>
        <div class="value"><?= $owner ? $escape($owner->name()) : $translate('[no owner]') ?></div>
    </div>

    <?php $bodies = $annotation->bodies(); ?>
    <div class="meta-group">
        <h4><?= $translate('Bodies') ?></h4>
        <?php if (count($bodies)): ?>
            <?php foreach ($bodies as $body): ?>
            <div class="value annotation-body"><?= $body->displayTitle() ?></div>
            <?php endforeach; ?>
        <?php else: ?>
            <p class="no-resources"><?= $translate('This annotation has no bodies.') ?></p>
        <?php endif; ?>
    </div>

    <?php $targets = $annotation->targets(); ?>
    <div class="meta-group">
        <h4><?= $translate('Targets') ?></h4>
        <?php if (count($targets)): ?>
        <?php foreach ($targets as $target): ?>
        <div class="value">
            <?= $target->displayTitle() ?>
        </div>
        <?php endforeach; ?>
        <?php else: ?>
        <p class="no-resources"><?= $translate('This annotation has no targets.') ?></p>
        <?php endif; ?>
    </div>

    <?php $this->trigger('view.details', ['entity' => $resource]); ?>
</div>
